# Generated by Django 5.0 on 2023-12-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Training', 'Training'), ('Personal coach', 'Personal coach')], max_length=20, null=True),
        ),
    ]
