# Generated by Django 5.0 on 2023-12-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(default='imagenes_ejercicios/defaul', upload_to='imagenes_ejercicios'),
        ),
    ]
